sudo: required

services:
  - docker

branches:
  only:
    - master

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

script:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build --no-cache=true -t $DOCKER_REPO:$COMMIT .

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker tag $DOCKER_REPO:$COMMIT $DOCKER_REPO:$TAG
  - docker tag $DOCKER_REPO:$COMMIT $DOCKER_REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_REPO
