name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint-backend
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.40.1
          working-directory: packages/backend
      - name: golangci-lint-kvg-collector
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.40.1
          working-directory: packages/kvg-collector
