name: JS linting

on:
  push:
    tags:
      - v*
    branches:
      - main
    paths:
      - 'lerna.json'
      - 'yarn.lock'
      - 'packages/app/package.json'
      - 'packages/app/**.vue'
      - 'packages/app/**.js'
  pull_request:
    paths:
      - 'lerna.json'
      - 'yarn.lock'
      - 'packages/app/package.json'
      - 'packages/app/**.vue'
      - 'packages/app/**.js'

env:
  YARN_CACHE_FOLDER: ~/.yarn

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ${{ env.YARN_CACHE_FOLDER }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn --frozen-lockfile
      - run: yarn lint
